AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Resources:
  tcsVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: Name
         Value: tcs-vpc
  tcsInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: tcs-igw
  tcsigwAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
         Ref: tcsVPC
      InternetGatewayId:
         Ref: tcsInternetGateway
  pubSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref tcsVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: "true"
      Tags:
      - Key: Name
        Value: pub-subnet
  pvtSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref tcsVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-east-1b"
      Tags:
      - Key: Name
        Value: pvt-subnet
  pvt2Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref tcsVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "us-east-1c"
      Tags:
      - Key: Name
        Value: pvt2-subnet
  pubRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: tcsVPC
      Tags:
      - Key: Name
        Value: pub-route
  pvtRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: tcsVPC
      Tags:
      - Key: Name
        Value: pvt-route
  pubigwRoute:
    Type: AWS::EC2::Route
    DependsOn: tcsigwAttachGateway
    Properties:
       RouteTableId:
         Ref: pubRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: tcsInternetGateway
  pubrtpubSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: pubSubnet
      RouteTableId:
        Ref: pubRouteTable
  pvtrtpvtSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: pvtSubnet
      RouteTableId:
        Ref: pvtRouteTable
  pvtrtpvt2SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: pvt2Subnet
      RouteTableId:
        Ref: pvtRouteTable